application:
  telegram:
    api-key: ${API_KEY}
    bot-enable: false
    limit: 100
    bot-username: gachimuachi_bot
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=gachi-bot}
    password: ${DATABASE_USER:root}
    username: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    com.github.telegramgachibot: debug
