application:
  telegram:
    api-key: ${API_KEY}
    bot-enable: false
    limit: 100
    bot-username: gachimuachi_bot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gachi-bot
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    com.github.telegramgachibot: debug
