version: '2'

services:
  app:
    image: 'telegram-gachi-bot:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/compose-postgres?currentSchema=gachi-bot
      - DATABASE_USER=compose-postgres
      - DATABASE_PASSWORD=compose-postgres
      - DDL_AUTO=update
      - API_KEY=
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"